//! File classification support for effort size-basis calculations.
//!
//! This module coordinates `.gitattributes` classification, generated/vendored
//! sentinels, and heuristic path tagging. Size-basis aggregation stays in the
//! parent module.

use std::path::{Path, PathBuf};
use std::{fs, io::BufRead, io::BufReader};

use tokmd_types::FileRow;

mod gitattributes;

use gitattributes::matches_path_pattern;
pub(super) use gitattributes::{GitAttrRule, load_gitattributes};

#[derive(Debug, Clone, Copy)]
pub(super) enum FileKind {
    Core,
    Infra,
    Build,
    Docs,
    Tests,
    Generated,
    Vendored,
    Api,
    Ffi,
    Ui,
    Data,
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub(super) enum ClassKind {
    Unknown,
    Generated,
    Vendored,
}

impl ClassKind {
    #[allow(dead_code)]
    fn confidence_boost(self) -> f64 {
        match self {
            Self::Generated | Self::Vendored => 1.0,
            Self::Unknown => 0.0,
        }
    }
}

pub(super) fn classify_row(
    root: &Path,
    path: &str,
    rules: &[GitAttrRule],
    row: &FileRow,
) -> (ClassKind, FileKind) {
    let _lower = path.to_lowercase();

    for rule in rules {
        if matches_path_pattern(path, root, &rule.pattern) {
            return (
                rule.kind,
                match rule.kind {
                    ClassKind::Generated => FileKind::Generated,
                    ClassKind::Vendored => FileKind::Vendored,
                    ClassKind::Unknown => FileKind::Core,
                },
            );
        }
    }

    let kind = if looks_generated_dir(path) || has_generated_sentinel(root, path) {
        FileKind::Generated
    } else if looks_vendored_dir(path) {
        FileKind::Vendored
    } else if looks_test_path(path) {
        FileKind::Tests
    } else if looks_doc_path(path, row) {
        FileKind::Docs
    } else if looks_api_path(path) {
        FileKind::Api
    } else if looks_ffi_path(path) {
        FileKind::Ffi
    } else if looks_ui_path(path) {
        FileKind::Ui
    } else if looks_data_path(path) {
        FileKind::Data
    } else if looks_build_path(path) {
        FileKind::Build
    } else if looks_infra_path(row) {
        FileKind::Infra
    } else {
        FileKind::Core
    };

    let class = match kind {
        FileKind::Generated => ClassKind::Generated,
        FileKind::Vendored => ClassKind::Vendored,
        _ => ClassKind::Unknown,
    };

    (class, kind)
}

pub(super) fn tag_name(kind: &FileKind) -> &str {
    match kind {
        FileKind::Core => "core",
        FileKind::Infra => "infra",
        FileKind::Build => "build",
        FileKind::Docs => "docs",
        FileKind::Tests => "tests",
        FileKind::Generated => "generated",
        FileKind::Vendored => "vendored",
        FileKind::Api => "api",
        FileKind::Ffi => "ffi",
        FileKind::Ui => "ui",
        FileKind::Data => "data",
    }
}

fn has_host_root(root: &Path) -> bool {
    !root.as_os_str().is_empty()
}

fn has_generated_sentinel(root: &Path, path: &str) -> bool {
    if !has_host_root(root) {
        return false;
    }

    let full = root.join(PathBuf::from(path));
    let file = match fs::File::open(&full) {
        Ok(f) => f,
        Err(_) => return false,
    };

    let reader = BufReader::new(file);
    for line in reader.lines().take(40).flatten() {
        if is_generated_sentinel(&line) {
            return true;
        }
    }
    false
}

fn is_generated_sentinel(text: &str) -> bool {
    let lower = text.to_lowercase();
    lower.contains("generated by")
        || lower.contains("do not edit")
        || lower.contains("auto-generated")
        || lower.contains("autogenerated")
}

fn looks_generated_dir(path: &str) -> bool {
    let lower = path.to_lowercase();
    lower.contains("/generated/")
        || lower.contains("/dist/")
        || lower.contains("/build/")
        || lower.contains("/target/")
        || lower.ends_with(".min.js")
        || lower.ends_with(".map")
}

fn looks_vendored_dir(path: &str) -> bool {
    let lower = path.to_lowercase();
    lower.contains("/vendor/")
        || lower.contains("/third_party/")
        || lower.contains("/node_modules/")
        || lower.contains("/deps/")
}

fn looks_test_path(path: &str) -> bool {
    let lower = path.to_lowercase();
    lower.contains("/test/")
        || lower.contains("/tests/")
        || lower.contains("__tests__")
        || lower.contains("/spec/")
        || lower.contains("/specs/")
        || lower.ends_with("_test.rs")
}

fn looks_doc_path(path: &str, row: &FileRow) -> bool {
    let lower = path.to_lowercase();
    row.lang.to_lowercase() == "markdown"
        || lower.contains("/docs/")
        || lower.ends_with("readme.md")
}

fn looks_api_path(path: &str) -> bool {
    let lower = path.to_lowercase();
    lower.contains("/api/") || lower.ends_with(".proto") || lower.ends_with(".openapi.json")
}

fn looks_ffi_path(path: &str) -> bool {
    let lower = path.to_lowercase();
    lower.contains("/ffi/") || lower.contains("/bindings/") || lower.ends_with("_ffi.rs")
}

fn looks_ui_path(path: &str) -> bool {
    let lower = path.to_lowercase();
    lower.contains("/ui/") || lower.contains("/web/") || lower.contains("/frontend/")
}

fn looks_data_path(path: &str) -> bool {
    let lower = path.to_lowercase();
    lower.contains("/data/") || lower.contains("/resources/") || lower.contains("/assets/")
}

fn looks_build_path(path: &str) -> bool {
    let lower = path.to_lowercase();
    lower.ends_with(".yml")
        || lower.ends_with(".yaml")
        || lower.ends_with(".toml")
        || lower.contains("/ci/")
        || lower.contains("/.github/")
}

fn looks_infra_path(row: &FileRow) -> bool {
    tokmd_analysis_types::is_infra_lang(&row.lang)
}
